### ISSUE TITLE
Game-master requires too many database connections and crashes

### ISSUE THREAD

**Issue by jakmeier** [jakmeier/paddlers-browser-game#9]
### Bug description
Presumably when there are too many active players, the game-master runs out of DB connections. 
Wiping all player data from the game DB fixed the issue. Restarting alone did not work, however.

### Workarounds
As a first step and temporal workaround, the game-master should not panic when the R2D2 pool has no connections left.

### Possible solutions
More investigation is needed to find out where the connections from the R2D2 pool are all stuck.
Things to try:
- Increase R2D2 pool size (default is 10, PostgreSQL is currently at 100)
- Restructure game master to use fewer DB connections

### Additional information
stack backtrace:
thread '<unnamed>' panicked at 'Couldn't get DB connection: Error(None)', src/db.rs:24:12
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1268
  14: <actix::sync::SyncContextEnvelope<A,M> as actix::address::envelope::EnvelopeProxy>::handle
  15: actix::sync::SyncContext<A>::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by jakmeier** [comment]
Fix available in patch v0.1.2a.
- The problem was the attack spawner, which took a connection and moved it into a closure that will only be called later. Not, the connection is only taken when the closure is executed.
- As additional measure, I also increased the game-master's db pool size for production build and decreased in local build

**Comment by jakmeier** [comment]
New version live on https://demo.paddlers.ch/
